cd /content/;
echo "installing tensorflow";
pip install tensorflow;
echo "installed tensorflow";
git clone https://github.com/tensorflow/models.git;
echo "cloned models";
cd /content/models/research;
echo "protoc object_detection";
protoc object_detection/protos/*.proto --python_out=.;
git clone https://github.com/cocodataset/cocoapi.git;
echo "cloned cocoapi";
cd /content/models/research/cocoapi/PythonAPI;
echo "make";
make;
echo "cp pycocotools";
cp -r pycocotools /content/models/research;
cd /content/models/research/;
echo "cp object_detection";
cp object_detection/packages/tf2/setup.py .;
echo "installing .";
python -m pip install .;
echo "successfully installed";  
echo "***************************************************";
echo "***************************************************";  
echo "YOU CAN DELETE main.sh NOW";